FORMAT: 1A
HOST: https://marketplace.matrix42.com/slim/api/v1/

# Matrix42 Marketplace Slim API v1

This API returns all Matrix42 Marketplace Products and Orders to be implemented against, in the Matrix42 Applications. 

# Product API Root [/products]

This resource provides all products.

## Retrieve all Products [GET]

+ Response 200 (application/json)

        {
            "products": [
                "id": 599,
                "title": "Dropbox for Business",
                "description": "<p>Integration of Dropbox for Business in MyWorkspace.</p>"
                "created_at": "2015-05-22T13:59:53Z",
                "updated_at": "2015-05-30T22:03:47Z",
                "type": "simple",
                "status": "publish",
                "permalink": "https://local.matrix42.com/product/dropbox-for-business/",
                "sku": "",
                "price": "0.00",
                "related_ids": [
                    116,
                    248,
                    330,
                    333,
                    370
                ],
                "categories": [
                    "MyWorkspace"
                ],
                "featured_src": "http://m42marketplacemediathek.blob.core.windows.net/matrix42-ag/2015/05/glyph-vflK-Wlfk.png",
                "img_screenshots": [
                    {
                        "id": 604,
                        "created_at": "2015-05-19T13:56:52Z",
                        "updated_at": "2015-05-19T13:56:52Z",
                        "src": "http://m42marketplacemediathek.blob.core.windows.net/matrix42-ag/2015/05/glyph-vflK-Wlfk.png",
                        "title": "glyph-vflK-Wlfk",
                        "alt": "",
                      "position": 0
                    }
                ],
                "downloads": [
                    {
                       "id": "6713f15bc8abd858f7702c7d36e73e34",
                       "name": "metadata-1.0.zip",
                        "file": "https://m42marketplacemediathek.blob.core.windows.net/matrix42-ag/2015/05/MyWorkspace-DropboxforBusiness-1.00.zip?st=2015-05-30T21%3A48Z&se=2015-05-31T10%3A03Z&sr=b&sp=r&sig=xGuissZyGsphe%2Bjyf3VOhdC08DGNF0nzcDan3Ypq%2BO8%3D&sv=2012-02-12"
                    }
                ],
            ]
        }

## Group Question

Resources related to questions in the API.

## Question [/questions/{question_id}]

A Question object has the following attributes:

+ question
+ published_at - An ISO8601 date when the question was published.
+ url
+ choices - An array of Choice objects.

+ Parameters
    + question_id: 1 (required, number) - ID of the Question in form of an integer

### View a Questions Detail [GET]

+ Response 200 (application/json)

        {
            "question": "Favourite programming language?",
            "published_at": "2014-11-11T08:40:51.620Z",
            "url": "/questions/1",
            "choices": [
                {
                    "choice": "Swift",
                    "url": "/questions/1/choices/1",
                    "votes": 2048
                }, {
                    "choice": "Python",
                    "url": "/questions/1/choices/2",
                    "votes": 1024
                }, {
                    "choice": "Objective-C",
                    "url": "/questions/1/choices/3",
                    "votes": 512
                }, {
                    "choice": "Ruby",
                    "url": "/questions/1/choices/4",
                    "votes": 256
                }
            ]
        }

## Choice [/questions/{question_id}/choices/{choice_id}]

+ Parameters
    + question_id: 1 (required, number) - ID of the Question in form of an integer
    + choice_id: 1 (required, number) - ID of the Choice in form of an integer

### Vote on a Choice [POST]

This action allows you to vote on a question's choice.

+ Response 201

    + Headers

            Location: /questions/1

## Questions Collection [/questions{?page}]

+ Parameters
    + page: 1 (optional, number) - The page of questions to return

### List All Questions [GET]

+ Response 200 (application/json)

    + Headers

            Link: </questions?page=2>; rel="next"

    + Body

            [
                {
                    "question": "Favourite programming language?",
                    "published_at": "2014-11-11T08:40:51.620Z",
                    "url": "/questions/1",
                    "choices": [
                        {
                            "choice": "Swift",
                            "url": "/questions/1/choices/1",
                            "votes": 2048
                        }, {
                            "choice": "Python",
                            "url": "/questions/1/choices/2",
                            "votes": 1024
                        }, {
                            "choice": "Objective-C",
                            "url": "/questions/1/choices/3",
                            "votes": 512
                        }, {
                            "choice": "Ruby",
                            "url": "/questions/1/choices/4",
                            "votes": 256
                        }
                    ]
                }
            ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ question (string) - The question
+ choices (array[string]) - A collection of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2014-11-11T08:40:51.620Z",
                "url": "/questions/2",
                "choices": [
                    {
                        "choice": "Swift",
                        "url": "/questions/2/choices/1",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "url": "/questions/2/choices/2",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "url": "/questions/2/choices/3",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "url": "/questions/2/choices/4",
                        "votes": 0
                    }
                ]
            }
