FORMAT: 1A
HOST: https://marketplace.matrix42.com/slim/api/v1/

# Matrix42 Marketplace Slim API v1

This API returns all Matrix42 Marketplace Products and Orders to be implemented against, in the Matrix42 Applications. 

# Product API Root [/products]

This route provides all products.

## View all Products [GET]

+ Response 200 (application/json)

        {
            "products": [
                "id": 599,
                "title": "Dropbox for Business",
                "description": "<p>Integration of Dropbox for Business in MyWorkspace.</p>"
                "created_at": "2015-05-22T13:59:53Z",
                "updated_at": "2015-05-30T22:03:47Z",
                "type": "simple",
                "status": "publish",
                "permalink": "https://local.matrix42.com/product/dropbox-for-business/",
                "sku": "",
                "price": "0.00",
                "img_featured": "http://m42marketplacemediathek.blob.core.windows.net/matrix42-ag/2015/05/glyph-vflK-Wlfk.png",
                "img_screenshots": [
                    {
                        "id": 604,
                        "created_at": "2015-05-19T13:56:52Z",
                        "updated_at": "2015-05-19T13:56:52Z",
                        "src": "http://m42marketplacemediathek.blob.core.windows.net/matrix42-ag/2015/05/glyph-vflK-Wlfk.png",
                        "title": "glyph-vflK-Wlfk",
                        "alt": "",
                        "position": 0
                    }
                ],
                "related_ids": [
                    116,
                    248,
                    330,
                    333,
                    370
                ],
                "categories": [
                    "MyWorkspace"
                ],
                "downloads": [
                    {
                        "id": "6713f15bc8abd858f7702c7d36e73e34",
                        "name": "metadata-1.0.zip",
                        "file": "https://m42marketplacemediathek.blob.core.windows.net/matrix42-ag/2015/05/MyWorkspace-DropboxforBusiness-1.00.zip?st=2015-05-30T21%3A48Z&se=2015-05-31T10%3A03Z&sr=b&sp=r&sig=xGuissZyGsphe%2Bjyf3VOhdC08DGNF0nzcDan3Ypq%2BO8%3D&sv=2012-02-12"
                    }
                ]
            ]
        }

## Product [/products/{product_id}]

A Product has the following attributes:

+ id
+ title
+ description
+ created_date - An ISO8601 date when the product was created.
+ update_at - An ISO8601 date when the product was updated.
+ type - WooCommerce Product type. Simple, Simple Subscription
+ status
+ permalink
+ sku - unique bookkeeping identifier
+ price - The target price without a currency
+ img_featured - The featured image URL
+ img_screenshots - An array with all screenshots
+ related_ids - An array with all ids that are somehow connected with this product
+ $subscription_ids - An array of all depending subscriptions
+ categories - An array of all categories
+ downloads - An array with all downloads

+ Parameters
    + product_id: 1 (required, number) - ID of the Product in form of an integer

### View a Product Detail [GET]

+ Response 200 (application/json)

        {    
            "id": 599,
            "title": "Dropbox for Business",
            "description": "<p>Integration of Dropbox for Business in MyWorkspace.</p>"
            "created_at": "2015-05-22T13:59:53Z",
            "updated_at": "2015-05-30T22:03:47Z",
            "type": "simple",
            "status": "publish",
            "permalink": "https://local.matrix42.com/product/dropbox-for-business/",
            "sku": "",
            "price": "0.00",
            "img_featured": "http://m42marketplacemediathek.blob.core.windows.net/matrix42-ag/2015/05/glyph-vflK-Wlfk.png",
            "img_screenshots": [
                {
                    "id": 604,
                    "created_at": "2015-05-19T13:56:52Z",
                    "updated_at": "2015-05-19T13:56:52Z",
                    "src": "http://m42marketplacemediathek.blob.core.windows.net/matrix42-ag/2015/05/glyph-vflK-Wlfk.png",
                    "title": "glyph-vflK-Wlfk",
                    "alt": "",
                    "position": 0
                }
            ],
            "related_ids": [
                116,
                248,
                330,
                333,
                370
            ],
            "categories": [
                "MyWorkspace"
            ],
            "downloads": [
                {
                    "id": "6713f15bc8abd858f7702c7d36e73e34",
                    "name": "metadata-1.0.zip",
                    "file": "https://m42marketplacemediathek.blob.core.windows.net/matrix42-ag/2015/05/MyWorkspace-DropboxforBusiness-1.00.zip?st=2015-05-30T21%3A48Z&se=2015-05-31T10%3A03Z&sr=b&sp=r&sig=xGuissZyGsphe%2Bjyf3VOhdC08DGNF0nzcDan3Ypq%2BO8%3D&sv=2012-02-12"
                }
            ]
        }